; #FUNCTION# ====================================================================================================================
; Name ..........: CGB GUI Design
; Description ...: This file Includes GUI Design
; Syntax ........:
; Parameters ....: None
; Return values .: None
; Author ........: GKevinOD (2014)
; Modified ......: DkEd, Hervidero (2015)
; Remarks .......: This file is part of ClashGameBot. Copyright 2015
;                  ClashGameBot is distributed under the terms of the GNU GPL
; Related .......:
; Link ..........:
; Example .......: No
; ===============================================================================================================================

;~ -------------------------------------------------------------
;~ Donate Tab
;~ -------------------------------------------------------------
$tabDonate = GUICtrlCreateTabItem(getLocaleString("tabDonate"))
	Local $x = 30, $y = 150
	$grpDonation = GUICtrlCreateGroup(getLocaleString("grpDonation"), $x - 20, $y - 20, 450, 65)
		GUICtrlCreateIcon($pIconLib, $eIcnCC, $x - 5, $y, 32, 32, $BS_ICON)
		$chkRequest = GUICtrlCreateCheckbox(getLocaleString("chkRequest"), $x + 35, $y + 5, -1, -1)
			GUICtrlSetOnEvent(-1, "chkRequest")
		$txtRequest = GUICtrlCreateInput(getLocaleString("txtRequest"), $x + 115, $y + 5, 305, -1)
			GUICtrlSetState(-1, $GUI_DISABLE)
			GUICtrlSetTip(-1, getLocaleString("tipRequest"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

$y += 70
$grpTroopselection = GUICtrlCreateGroup(getLocaleString("grpTroopselection"), $x - 20, $y - 20, 450, 110)
$x -=2
	$lblBtnBarbarians = GUICtrlCreateLabel("", $x - 12, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnBarbarians = GUICtrlCreateButton(getLocaleString("troopBarbarians"), $x - 10, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonBarbarian, 1)
		GUICtrlSetOnEvent(-1, "btnDonateBarbarians")
	$lblBtnArchers = GUICtrlCreateLabel("", $x + 28, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnArchers = GUICtrlCreateButton(getLocaleString("troopArchers"), $x + 30, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonArcher, 1)
		GUICtrlSetOnEvent(-1, "btnDonateArchers")
	$lblBtnGiants = GUICtrlCreateLabel("", $x + 68, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnGiants = GUICtrlCreateButton(getLocaleString("troopGiants"), $x + 70, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonGiant, 1)
		GUICtrlSetOnEvent(-1, "btnDonateGiants")
	$lblBtnGoblins = GUICtrlCreateLabel("", $x + 108, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnGoblins = GUICtrlCreateButton(getLocaleString("troopGoblins"), $x + 110, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonGoblin, 1)
		GUICtrlSetOnEvent(-1, "btnDonateGoblins")
	$lblBtnWallBreakers = GUICtrlCreateLabel("", $x + 148, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnWallBreakers = GUICtrlCreateButton(getLocaleString("troopWallBreakers"), $x + 150, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonWallBreaker, 1)
		GUICtrlSetOnEvent(-1, "btnDonateWallBreakers")

	$btnBlacklist = GUICtrlCreateButton("Blacklist", $x + 191, $y + 24, 32, 32, $BS_ICON)
		GUICtrlSetImage (-1, $pIconLib, $eIcnDonBlacklist, 1)
		GUICtrlSetOnEvent(-1, "btnDonateBlacklist")

	$lblBtnMinions = GUICtrlCreateLabel("", $x + 223, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnMinions = GUICtrlCreateButton(getLocaleString("troopMinions"), $x + 225, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonMinion, 1)
		GUICtrlSetOnEvent(-1, "btnDonateMinions")
	$lblBtnHogRiders = GUICtrlCreateLabel("", $x + 263, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnHogRiders = GUICtrlCreateButton(getLocaleString("troopHogRiders"), $x + 265, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonHogRider, 1)
		GUICtrlSetOnEvent(-1, "btnDonateHogRiders")
	$lblBtnValkyries = GUICtrlCreateLabel("", $x + 303, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnValkyries = GUICtrlCreateButton(getLocaleString("troopValkyries"), $x+ 305, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonValkyrie, 1)
		GUICtrlSetOnEvent(-1, "btnDonateValkyries")

$y += 40
	$lblBtnBalloons = GUICtrlCreateLabel("", $x - 12, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnBalloons = GUICtrlCreateButton(getLocaleString("troopBalloons"), $x - 10, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonBalloon, 1)
		GUICtrlSetOnEvent(-1, "btnDonateBalloons")
	$lblBtnWizards = GUICtrlCreateLabel("", $x + 28, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnWizards = GUICtrlCreateButton(getLocaleString("troopWizards"), $x + 30, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonWizard, 1)
		GUICtrlSetOnEvent(-1, "btnDonateWizards")
	$lblBtnHealers = GUICtrlCreateLabel("", $x + 68, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnHealers = GUICtrlCreateButton(getLocaleString("troopHealers"), $x + 70, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonHealer, 1)
		GUICtrlSetOnEvent(-1, "btnDonateHealers")
	$lblBtnDragons = GUICtrlCreateLabel("", $x + 108, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnDragons = GUICtrlCreateButton(getLocaleString("troopDragons"), $x + 110, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage(-1, $pIconLib, $eIcnDonDragon, 1)
		GUICtrlSetOnEvent(-1, "btnDonateDragons")
	$lblBtnPekkas = GUICtrlCreateLabel("", $x + 148, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnPekkas = GUICtrlCreateButton(getLocaleString("troopPekkas"), $x + 150, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage (-1, $pIconLib, $eIcnDonPekka, 1)
		GUICtrlSetOnEvent(-1, "btnDonatePekkas")

	$lblBtnGolems = GUICtrlCreateLabel("", $x + 223, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnGolems = GUICtrlCreateButton(getLocaleString("troopGolems"), $x + 225, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage (-1, $pIconLib, $eIcnDonGolem, 1)
		GUICtrlSetOnEvent(-1, "btnDonateGolems")
	$lblBtnWitches = GUICtrlCreateLabel("", $x + 263, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnWitches = GUICtrlCreateButton(getLocaleString("troopWitches"), $x+ 265, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage (-1, $pIconLib, $eIcnDonWitch, 1)
		GUICtrlSetOnEvent(-1, "btnDonateWitches")
	$lblBtnLavaHounds = GUICtrlCreateLabel("", $x + 303, $y - 2, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnLavaHounds = GUICtrlCreateButton(getLocaleString("troopLavaHounds"), $x + 305, $y, 38, 38, $BS_ICON)
		GUICtrlSetImage (-1, $pIconLib, $eIcnDonLavaHound, 1)
		GUICtrlSetOnEvent(-1, "btnDonateLavaHounds")

	;;; Custom Combination Donate by ChiefM3
	$lblBtnCustom = GUICtrlCreateLabel("", $x + 363, $y - 22, 42, 42)
		GUICtrlSetBkColor(-1, $GUI_BKCOLOR_TRANSPARENT)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnCustom = GUICtrlCreateButton(getLocaleString("troopCustom"), $x + 365, $y - 20, 38, 38, $BS_ICON)
		GUICtrlSetImage (-1, $pIconLib, $eIcnDonCustom, 1) ;;; cross swords icon
		GUICtrlSetOnEvent(-1, "btnDonateCustom")

$x += 2
$y += 75
	$grpBarbarians = GUICtrlCreateGroup(getLocaleString("troopBarbarians"), $x - 20, $y - 20, 450, 190)
		$picDonateBarbarians = GUICtrlCreateIcon($pIconLib, $eIcnDonBarbarian, $x + 215, $y, 64, 64, $BS_ICON)
		$chkDonateBarbarians = GUICtrlCreateCheckbox(getLocaleString("donateBarbarians"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetTip(-1, getLocaleString("tipDonateBarbarians"))
			GUICtrlSetOnEvent(-1, "chkDonateBarbarians")
		$chkDonateAllBarbarians = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetTip(-1, getLocaleString("donateAllBarbarians") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllBarbarians")
		$lblDonateBarbarians = GUICtrlCreateLabel(getLocaleString("keywordsBarbarians"), $x - 5, $y + 5, -1, -1)
		$txtDonateBarbarians = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetData(-1, StringFormat("barbarians\r\nbarb"))
			GUICtrlSetTip(-1, getLocaleString("keywordsBarbarians"))
		$lblBlacklistBarbarians = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
		$txtBlacklistBarbarians = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no barbarians\r\nno barb\r\nbarbarians no\r\nbarb no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistBarbarians"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpArchers = GUICtrlCreateGroup(getLocaleString("troopArchers"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateArchers = GUICtrlCreateIcon($pIconLib, $eIcnDonArcher, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateArchers = GUICtrlCreateCheckbox(getLocaleString("donateArchers"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonateArchers"))
			GUICtrlSetOnEvent(-1, "chkDonateArchers")
		$chkDonateAllArchers = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllArchers") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllArchers")
		$lblDonateArchers = GUICtrlCreateLabel(getLocaleString("keywordsArchers"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateArchers = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("archers\r\narch"))
			GUICtrlSetTip(-1, getLocaleString("keywordsArchers"))
		$lblBlacklistArchers = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistArchers = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no archers\r\nno arch\r\narchers no\r\narch no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistArchers"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpGiants = GUICtrlCreateGroup(getLocaleString("troopGiants"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateGiants = GUICtrlCreateIcon($pIconLib, $eIcnDonGiant, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateGiants = GUICtrlCreateCheckbox(getLocaleString("donateGiants"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonateGiants"))
			GUICtrlSetOnEvent(-1, "chkDonateGiants")
		$chkDonateAllGiants = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllGiants") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllGiants")
		$lblDonateGiants = GUICtrlCreateLabel(getLocaleString("keywordsGiants"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateGiants = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("giants\r\ngiant\r\nany\r\nreinforcements"))
			GUICtrlSetTip(-1, getLocaleString("keywordsGiants"))
		$lblBlacklistGiants = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistGiants = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no giants\r\ngiants no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistGiants"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpGoblins = GUICtrlCreateGroup(getLocaleString("troopGoblins"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateGoblins = GUICtrlCreateIcon($pIconLib, $eIcnDonGoblin, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateGoblins = GUICtrlCreateCheckbox(getLocaleString("donateGoblins"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonateGoblins"))
			GUICtrlSetOnEvent(-1, "chkDonateGoblins")
		$chkDonateAllGoblins = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllGoblins") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllGoblins")
		$lblDonateGoblins = GUICtrlCreateLabel(getLocaleString("keywordsGoblins"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateGoblins = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("goblins\r\ngoblin"))
			GUICtrlSetTip(-1, getLocaleString("keywordsGoblins"))
		$lblBlacklistGoblins = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistGoblins = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no goblins\r\ngoblins no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistgoblins"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpWallBreakers = GUICtrlCreateGroup(getLocaleString("troopWallBreakers"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateWallBreakers = GUICtrlCreateIcon($pIconLib, $eIcnDonWallBreaker, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateWallBreakers = GUICtrlCreateCheckbox(getLocaleString("donateWallBreakers"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonateWallBreakers"))
			GUICtrlSetOnEvent(-1, "chkDonateWallBreakers")
		$chkDonateAllWallBreakers = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllWallBreakers") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllWallBreakers")
		$lblDonateWallBreakers = GUICtrlCreateLabel(getLocaleString("keywordsWallBreakers"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateWallBreakers = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("wall breakers\r\nbreaker"))
			GUICtrlSetTip(-1, getLocaleString("keywordsWallBreakers"))
		$lblBlacklistWallBreakers = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistWallBreakers = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no wall breakers\r\nwall breakers no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistWallBreakers"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpBalloons = GUICtrlCreateGroup(getLocaleString("troopBalloons"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateBalloons = GUICtrlCreateIcon($pIconLib, $eIcnDonBalloon, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateBalloons = GUICtrlCreateCheckbox(getLocaleString("donateBalloons"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonateBalloons"))
			GUICtrlSetOnEvent(-1, "chkDonateBalloons")
		$chkDonateAllBalloons = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllBalloons") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllBalloons")
		$lblDonateBalloons = GUICtrlCreateLabel(getLocaleString("keywordsBalloons"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateBalloons = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("balloons\r\nballoon"))
			GUICtrlSetTip(-1, getLocaleString("keywordsBalloons"))
		$lblBlacklistBalloons = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistBalloons = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no balloons\r\nballoons no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistBalloons"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpWizards = GUICtrlCreateGroup(getLocaleString("troopWizards"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateWizards = GUICtrlCreateIcon($pIconLib, $eIcnDonWizard, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateWizards = GUICtrlCreateCheckbox(getLocaleString("donateWizards"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonateWizards"))
			GUICtrlSetOnEvent(-1, "chkDonateWizards")
		$chkDonateAllWizards = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllWizards") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllWizards")
		$lblDonateWizards = GUICtrlCreateLabel(getLocaleString("keywordsWizards"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateWizards = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("wizards\r\nwizard"))
			GUICtrlSetTip(-1, getLocaleString("keywordsWizards"))
		$lblBlacklistWizards = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistWizards = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no wizards\r\nwizards no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistWizards"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpHealers = GUICtrlCreateGroup(getLocaleString("troopHealers"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateHealers = GUICtrlCreateIcon($pIconLib, $eIcnDonHealer, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateHealers = GUICtrlCreateCheckbox(getLocaleString("donateHealers"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonateHealers"))
			GUICtrlSetOnEvent(-1, "chkDonateHealers")
		$chkDonateAllHealers = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllHealers") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllHealers")
		$lblDonateHealers = GUICtrlCreateLabel(getLocaleString("keywordsHealers"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateHealers = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("healer"))
			GUICtrlSetTip(-1, getLocaleString("keywordsHealers"))
		$lblBlacklistHealers = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistHealers = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no healer\r\nhealer no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistHealers"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpDragons = GUICtrlCreateGroup(getLocaleString("troopDragons"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateDragons = GUICtrlCreateIcon($pIconLib, $eIcnDonDragon, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateDragons = GUICtrlCreateCheckbox(getLocaleString("donateDragons"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonateDragons"))
			GUICtrlSetOnEvent(-1, "chkDonateDragons")
		$chkDonateAllDragons = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllDragons") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllDragons")
		$lblDonateDragons = GUICtrlCreateLabel(getLocaleString("keywordsDragons"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateDragons = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("dragon"))
			GUICtrlSetTip(-1, getLocaleString("keywordsDragons"))
		$lblBlacklistDragons = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistDragons = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no dragon\r\ndragon no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistDragons"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpPekkas = GUICtrlCreateGroup(getLocaleString("troopPekkas"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonatePekkas = GUICtrlCreateIcon($pIconLib, $eIcnDonPekka, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonatePekkas = GUICtrlCreateCheckbox(getLocaleString("donatePekkas"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonatePekkas"))
			GUICtrlSetOnEvent(-1, "chkDonatePekkas")
		$chkDonateAllPekkas = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllPekkas") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllPekkas")
		$lblDonatePekkas = GUICtrlCreateLabel(getLocaleString("keywordsPekkas"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonatePekkas = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("PEKKA\r\npekka"))
			GUICtrlSetTip(-1, getLocaleString("keywordsPekkas"))
		$lblBlacklistPekkas = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistPekkas = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no PEKKA\r\npekka no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistPekkas"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpMinions = GUICtrlCreateGroup(getLocaleString("troopMinions"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateMinions = GUICtrlCreateIcon($pIconLib, $eIcnDonMinion, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateMinions = GUICtrlCreateCheckbox(getLocaleString("donateMinions"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonateMinions"))
			GUICtrlSetOnEvent(-1, "chkDonateMinions")
		$chkDonateAllMinions = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllMinions") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllMinions")
		$lblDonateMinions = GUICtrlCreateLabel(getLocaleString("keywordsMinions"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateMinions = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("minions\r\nminion"))
			GUICtrlSetTip(-1, getLocaleString("keywordsMinions"))
		$lblBlacklistMinions = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistMinions = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no minions\r\nminions no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistMinions"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpHogRiders = GUICtrlCreateGroup(getLocaleString("troopHogRiders"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateHogRiders = GUICtrlCreateIcon($pIconLib, $eIcnDonHogRider, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateHogRiders = GUICtrlCreateCheckbox(getLocaleString("donateHogRiders"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonateHogRiders"))
			GUICtrlSetOnEvent(-1, "chkDonateHogRiders")
		$chkDonateAllHogRiders = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllHogRiders") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllHogRiders")
		$lblDonateHogRiders = GUICtrlCreateLabel(getLocaleString("keywordsHogRiders"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateHogRiders = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("hogriders\r\nhogs\r\nhog"))
			GUICtrlSetTip(-1, getLocaleString("keywordsHogRiders"))
		$lblBlacklistHogRiders = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistHogRiders = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no hogs\r\nhog no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistHogRiders"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpValkyries = GUICtrlCreateGroup(getLocaleString("troopValkyries"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateValkyries = GUICtrlCreateIcon($pIconLib, $eIcnDonValkyrie, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateValkyries = GUICtrlCreateCheckbox(getLocaleString("donateValkyries"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonateValkyries"))
			GUICtrlSetOnEvent(-1, "chkDonateValkyries")
		$chkDonateAllValkyries = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllValkyries") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllValkyries")
		$lblDonateValkyries = GUICtrlCreateLabel(getLocaleString("keywordsValkyries"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateValkyries = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("valkyries\r\nvalkyrie"))
			GUICtrlSetTip(-1, getLocaleString("keywordsValkyries"))
		$lblBlacklistValkyries = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistValkyries = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no valkyries\r\nvalkyries no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistValkyries"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpGolems = GUICtrlCreateGroup(getLocaleString("troopGolems"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateGolems = GUICtrlCreateIcon($pIconLib, $eIcnDonGolem, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateGolems = GUICtrlCreateCheckbox(getLocaleString("donateGolems"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonateGolems"))
			GUICtrlSetOnEvent(-1, "chkDonateGolems")
		$chkDonateAllGolems = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllGolems") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllGolems")
		$lblDonateGolems = GUICtrlCreateLabel(getLocaleString("keywordsGolems"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateGolems = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("golem"))
			GUICtrlSetTip(-1, getLocaleString("keywordsGolems"))
		$lblBlacklistGolems = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistGolems = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no golem\r\ngolem no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistGolems"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpWitches = GUICtrlCreateGroup(getLocaleString("troopWitches"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateWitches = GUICtrlCreateIcon($pIconLib, $eIcnDonWitch, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateWitches = GUICtrlCreateCheckbox(getLocaleString("donateWitches"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonateWitches"))
			GUICtrlSetOnEvent(-1, "chkDonateWitches")
		$chkDonateAllWitches = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllWitches") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllWitches")
		$lblDonateWitches = GUICtrlCreateLabel(getLocaleString("keywordsWitches"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateWitches = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("witches\r\nwitch"))
			GUICtrlSetTip(-1, getLocaleString("keywordsWitches"))
		$lblBlacklistWitches = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistWitches = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no witches\r\nwitch no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistWitches"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpLavaHounds = GUICtrlCreateGroup(getLocaleString("troopLavaHounds"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateLavaHounds = GUICtrlCreateIcon($pIconLib, $eIcnDonLavaHound, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateLavaHounds = GUICtrlCreateCheckbox(getLocaleString("donateLavaHounds"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonateLavaHounds"))
			GUICtrlSetOnEvent(-1, "chkDonateLavaHounds")
		$chkDonateAllLavaHounds = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllLavaHounds") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllLavaHounds")
		$lblDonateLavaHounds = GUICtrlCreateLabel(getLocaleString("keywordsLavaHounds"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateLavaHounds = GUICtrlCreateEdit("", $x - 5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("lavahound\r\nhound\r\nlava"))
			GUICtrlSetTip(-1, getLocaleString("keywordsLavaHounds"))
		$lblBlacklistLavaHounds = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 70, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistLavaHounds = GUICtrlCreateEdit("", $x + 215, $y + 85, 200, 70, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("no lavahound\r\nhound no"))
			GUICtrlSetTip(-1, getLocaleString("blacklistLavaHounds"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	;;; Custom Combination Donate by ChiefM3, edit by Hervidero
	$grpCustom = GUICtrlCreateGroup(getLocaleString("troopCustom"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateCustom = GUICtrlCreateIcon($pIconLib, $eIcnDonCustom, $x + 215, $y, 64, 64, $BS_ICON)
		    GUICtrlSetState(-1, $GUI_HIDE)
		$chkDonateCustom = GUICtrlCreateCheckbox(getLocaleString("donateCustom"), $x + 285, $y + 10, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("tipDonateCustom"))
			GUICtrlSetOnEvent(-1, "chkDonateCustom")
		$chkDonateAllCustom = GUICtrlCreateCheckbox(getLocaleString("donateToAll"), $x + 285, $y + 30, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetTip(-1, getLocaleString("donateAllCustom") & @CRLF & getLocaleString("tipDonateToAll"))
			GUICtrlSetOnEvent(-1, "chkDonateAllCustom")
		$lblDonateCustom =     GUICtrlCreateLabel(getLocaleString("keywordsCustom"), $x - 5, $y + 90, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateCustom = GUICtrlCreateEdit("", $x - 5, $y + 105, 205, 50, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetData(-1, StringFormat("any\r\nneed"))
			GUICtrlSetTip(-1, getLocaleString("keywordsCustom"))

		$lblDonateCustom1 = GUICtrlCreateLabel(getLocaleString("lbDonateCustom1"), $x, $y + 4, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateCustom1 = GUICtrlCreateIcon($pIconLib, $eIcnDonWizard, $x + 25, $y, 24, 24)
			GUICtrlSetState(-1, $GUI_HIDE)
		$cmbDonateCustom1 = GUICtrlCreateCombo("", $x + 60, $y, 95, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
			GUICtrlSetData(-1, getLocaleString("cmbDonateCustom"), getLocaleString("cmbDonateCustomDefault1"))
			GUICtrlSetOnEvent(-1, "cmbDonateCustom")
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateCustom1 = GUICtrlCreateInput("2", $x + 165, $y, 30, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
			GUICtrlSetLimit(-1, 1)
			GUICtrlSetState(-1, $GUI_HIDE)

		$lblDonateCustom2 = GUICtrlCreateLabel(getLocaleString("lbDonateCustom2"), $x, $y + 29, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateCustom2 = GUICtrlCreateIcon($pIconLib, $eIcnDonArcher, $x + 25, $y + 25, 24, 24)
			GUICtrlSetState(-1, $GUI_HIDE)
		$cmbDonateCustom2 = GUICtrlCreateCombo("", $x + 60, $y + 25, 95, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
			GUICtrlSetData(-1, getLocaleString("cmbDonateCustom"), getLocaleString("cmbDonateCustomDefault2"))
			GUICtrlSetOnEvent(-1, "cmbDonateCustom")
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateCustom2 = GUICtrlCreateInput("3", $x + 165, $y + 25, 30, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
			GUICtrlSetLimit(-1, 1)
			GUICtrlSetState(-1, $GUI_HIDE)

		$lblDonateCustom3 = GUICtrlCreateLabel(getLocaleString("lbDonateCustom3"), $x, $y + 54, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateCustom3 = GUICtrlCreateIcon($pIconLib, $eIcnDonBarbarian, $x + 25, $y + 50, 24, 24)
			GUICtrlSetState(-1, $GUI_HIDE)
		$cmbDonateCustom3 = GUICtrlCreateCombo("", $x + 60, $y + 50, 95, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
			GUICtrlSetData(-1, getLocaleString("cmbDonateCustom"), getLocaleString("cmbDonateCustomDefault2"))
			GUICtrlSetOnEvent(-1, "cmbDonateCustom")
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtDonateCustom3 = GUICtrlCreateInput("1", $x + 165, $y + 50, 30, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
			GUICtrlSetLimit(-1, 1)
			GUICtrlSetState(-1, $GUI_HIDE)

		$lblBlacklistCustom = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x + 215, $y + 90, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklistCustom = GUICtrlCreateEdit("", $x + 215, $y + 105, 200, 50, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, StringFormat("only\r\njust"))
			GUICtrlSetTip(-1, getLocaleString("blacklistCustomTroops"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)

	$grpBlacklist = GUICtrlCreateGroup(getLocaleString("grpBlacklist"), $x - 20, $y - 20, 450, 190)
		GUICtrlSetState(-1, $GUI_HIDE)
		$picDonateBlacklist = GUICtrlCreateIcon($pIconLib, $eIcnDonBlacklist, $x + 215, $y, 64, 64, $BS_ICON)
			GUICtrlSetState(-1, $GUI_HIDE)
		$lblBlacklist = GUICtrlCreateLabel(getLocaleString("lbBlacklist"), $x - 5, $y + 5, -1, -1)
			GUICtrlSetState(-1, $GUI_HIDE)
		$txtBlacklist = GUICtrlCreateEdit("", $x -5, $y + 20, 205, 135, BitOR($ES_WANTRETURN, $ES_CENTER, $ES_AUTOVSCROLL))
			GUICtrlSetState(-1, $GUI_HIDE)
			GUICtrlSetBkColor ( -1, 0x505050)
			GUICtrlSetColor ( -1, $COLOR_WHITE)
			GUICtrlSetData(-1, getLocaleString("dataBlacklist",1))
			GUICtrlSetTip(-1, getLocaleString("tipBlacklist"))
	GUICtrlCreateGroup("", -99, -99, 1, 1)
