Func NameOfTroop($kind, $plurial = 0)
	Switch $kind
		Case $eBarb
			Return getLocaleString("eBarb")
		Case $eArch
			Return getLocaleString("eArch")
		Case $eGobl
			Return getLocaleString("eGobl")
		Case $eGiant
			Return getLocaleString("eGiant")
		Case $eWall
			Return getLocaleString("eWall")
		Case $eWiza
			Return getLocaleString("eWiza")
		Case $eBall
			Return getLocaleString("eBall")
	    Case $eHeal
			Return getLocaleString("eHeal")
	    Case $eDrag
			Return getLocaleString("eDrag")
	    Case $ePekk
			Return getLocaleString("ePekk")
		Case $eMini
			Return getLocaleString("eMini")
		Case $eHogs
			Return getLocaleString("eHogs")
		Case $eValk
			Return getLocaleString("eValk")
		Case $eWitc
			Return getLocaleString("eWitc")
		Case $eGole
			Return getLocaleString("eGole")
		Case $eLava
			Return getLocaleString("eLava")
		Case $eKing
			Return getLocaleString("eKing")
		Case $eQueen
			Return getLocaleString("eQueen")
		Case $eCastle
			Return getLocaleString("eCastle")
		Case $eLSpell
			Return getLocaleString("eLSpell")
		Case $eHSpell
			Return getLocaleString("eHSpell")
		Case $eRSpell
			Return getLocaleString("eRSpell")
	    Case $eJSpell
			Return getLocaleString("eJSpell")
		Case $eFSpell
			Return getLocaleString("eFSpell")
		Case $ePSpell
			Return getLocaleString("ePSpell")
		Case $eESpell
			Return getLocaleString("eESpell")
		Case $eHaSpell
			Return getLocaleString("eHaSpell")
		Case Else
			Return ""
	EndSwitch
EndFunc   ;==>NameOfTroop
